// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AnnouncementsPageDocumentDataSlicesSlice = AnnouncementBlockSlice;

/**
 * Content for Announcements Page documents
 */
interface AnnouncementsPageDocumentData {
  /**
   * Title field in *Announcements Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Announcements Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements_page.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Slice Zone field in *Announcements Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AnnouncementsPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Announcements Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: announcements_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Announcements Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: announcements_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Announcements Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: announcements_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Announcements Page document from Prismic
 *
 * - **API ID**: `announcements_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnnouncementsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AnnouncementsPageDocumentData>,
    "announcements_page",
    Lang
  >;

export type AllDocumentTypes = AnnouncementsPageDocument;

/**
 * Primary content in *AnnouncementBlocks → Items*
 */
export interface AnnouncementBlockSliceDefaultItem {
  /**
   * Announcement Title field in *AnnouncementBlocks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Accouncement field in *AnnouncementBlocks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_block.items[].announcement
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  announcement: prismic.RichTextField;
}

/**
 * Default variation for AnnouncementBlocks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AnnouncementBlockSliceDefaultItem>
>;

/**
 * Slice variation for *AnnouncementBlocks*
 */
type AnnouncementBlockSliceVariation = AnnouncementBlockSliceDefault;

/**
 * AnnouncementBlocks Shared Slice
 *
 * - **API ID**: `announcement_block`
 * - **Description**: AnnouncementBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBlockSlice = prismic.SharedSlice<
  "announcement_block",
  AnnouncementBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AnnouncementsPageDocument,
      AnnouncementsPageDocumentData,
      AnnouncementsPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnnouncementBlockSlice,
      AnnouncementBlockSliceDefaultItem,
      AnnouncementBlockSliceVariation,
      AnnouncementBlockSliceDefault,
    };
  }
}
